name 'ga_haproxy_default'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ga_haproxy_default'
long_description 'Installs/Configures ga_haproxy_default'
version '0.1.0'
