name 'ga_haproxy'
maintainer 'Sean McGowan'
maintainer_email 'spmcgowan@gmil.com'
license 'all_rights'
description 'Installs/Configures ga_haproxy'
long_description 'Installs/Configures ga_haproxy'
version '0.1.0'
